name: Static Analysis

on:
  workflow_dispatch:
  push:
    branches: [ "master", "*.*-dev" ]
  pull_request:
    branches: [ "master", "*.*-dev" ]

jobs:
  pint:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: make build-dev

    - name: Run Laravel Pint Analysis
      run: make test-code-style
